/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoDatos.AlojamientoData;
import AccesoDatos.CiudadData;
import Entidades.Alojamiento;
import Entidades.Ciudad;
import java.util.List;

/**
 *
 * @author Leo_1
 */
public class ModificarAlojamiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarAlojamiento
     */
    public ModificarAlojamiento() {
        initComponents();
        //cargarCombo();
        cargarCombo2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCbciudad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtalojamiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtimporte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtservicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRbestadomodificar = new javax.swing.JRadioButton();
        jbeliminar = new javax.swing.JButton();
        jbSalir1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCbModificar1 = new javax.swing.JComboBox<>();
        jbmodificar1 = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Modificar Alojamiento");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Modificar Alojamiento");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Seleccione una ciudad:");

        jCbciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbciudadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de alojamiento:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Servicio incluido:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Importe diario:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Estado:");

        jbeliminar.setText("Eliminar");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbSalir1.setText("Salir");
        jbSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalir1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Seleccione un alojamiento:");

        jCbModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbModificar1ActionPerformed(evt);
            }
        });

        jbmodificar1.setText("Modificar");
        jbmodificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificar1ActionPerformed(evt);
            }
        });

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbeliminar)
                                    .addComponent(jRbestadomodificar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbSalir1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCbciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtservicio)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 22, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtalojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jbmodificar1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCbciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCbModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtalojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jRbestadomodificar))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbeliminar)
                    .addComponent(jbSalir1)
                    .addComponent(jbmodificar1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
        // TODO add your handling code here:
        
        AlojamientoData ad = new AlojamientoData();
        Alojamiento al = new Alojamiento();
        int id = al.getIdAlojamiento();
        ad.eliminarAlojamiento(id);
        //al.setTipoAlojamiento(jtalojamiento.getText());
        //al.setServicio(jtservicio.getText());
        //al.setImporteDiario(Integer.parseInt(jtimporte.getText()));
        //al.setEstado(jRbestadomodificar.isEnabled());
        //ad.eliminarAlojamiento(al);
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalir1ActionPerformed
        // TODO add your handling code here:
        
        
        ModificarAlojamiento.this.setVisible(false);
        
    }//GEN-LAST:event_jbSalir1ActionPerformed

    private void jCbciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbciudadActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jCbciudadActionPerformed

    private void jCbModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbModificar1ActionPerformed
        // TODO add your handling code here:
        
        
        
        if(jCbModificar1.getItemCount() > 0){
        
            Alojamiento al = (Alojamiento)jCbModificar1.getSelectedItem();
            jtalojamiento.setText(al.getTipoAlojamiento());
            jtservicio.setText(al.getServicio());
            jtimporte.setText(al.getImporteDiario() + "");
            jRbestadomodificar.isEnabled();
        
        }
            
        
        
        
    }//GEN-LAST:event_jCbModificar1ActionPerformed

    private void jbmodificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbmodificar1ActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // TODO add your handling code here:
        if(jCbModificar1.getItemCount() > 0){
        
            jCbModificar1.removeAllItems();
            
        }
        Ciudad bu = (Ciudad)jCbciudad.getSelectedItem();
        AlojamientoData al= new AlojamientoData();
        List<Alojamiento> alojamientos = al.listarAlojamientos();
        for(Alojamiento alojamiento : alojamientos){
            
            if(alojamiento.getCiudadDestino().getIdCiudad() == bu.getIdCiudad()){
            
                jCbModificar1.addItem(alojamiento);
                
            }
        
        }
        
        
        
    }//GEN-LAST:event_jBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuscar;
    private javax.swing.JComboBox<Alojamiento> jCbModificar1;
    private javax.swing.JComboBox<Ciudad> jCbciudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRbestadomodificar;
    private javax.swing.JButton jbSalir1;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbmodificar1;
    private javax.swing.JTextField jtalojamiento;
    private javax.swing.JTextField jtimporte;
    private javax.swing.JTextField jtservicio;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        
        AlojamientoData cd = new AlojamientoData();
        List<Alojamiento> alojamientos = cd.listarAlojamientos();
        for (Alojamiento alojamiento : alojamientos) {
            jCbModificar1.addItem(alojamiento);
            //cbCiudadDestino.addItem(ciudad);
        }
    }
    
    private void cargarCombo2() {
        CiudadData cd = new CiudadData();
        List<Ciudad> ciudades = cd.listarCiudades();
        for (Ciudad ciudad : ciudades) {
            jCbciudad.addItem(ciudad);
            //cbCiudadDestino.addItem(ciudad);
        }
    }

}
